spring:
  application:
    name: @project.artifactId@
  datasource:
    url: jdbc:postgresql:///aluraflix
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    table: flyway_schema_history_aluraflix
server:
  port: 8080
management:
  server:
    port: 18080