spring:
  application:
    name: @project.artifactId@
  datasource:
    url: jdbc:postgresql:///aluraflix
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    table: flyway_schema_history_aluraflix
  redis:
    host: localhost
    port: 6379
server:
  port: 8080
management:
  server:
    port: 18080
  endpoints:
    web:
      exposure:
        include: "health,loggers,metrics,flyway"
cache-properties:
  caches:
    get-all-videos-public-free:
      name: getAllVideoDtosPublicAccessFree
      duration-in-minutes: 10
    get-all-video-dtos:
      name: getAllVideoDtos
      duration-in-minutes: 10
    get-video-dto-by-id:
      name: videoById
      duration-in-minutes: 10